apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pulp.fullname" . }}-pv
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storage.accessMode | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.VolumeReclaimPolicy }} 
  storageClassName: {{ include "pulp.fullname" . }}-storage
  local:
    path: {{ .Values.storage.pvpath }} 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - pulp
