apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
type: Opaque
data:
  database_fields.symmetric.key: {{ .Values.database_fields_symmetric_key | b64enc }}
  pulp_webserver.crt: {{ .Values.pulp_webserver_crt | b64enc }}
  pulp_webserver.key: {{ .Values.pulp_webserver_key | b64enc }}
  token_private_key.pem: {{ .Values.token_private_key_pem | b64enc }} 
  token_public_key.pem: {{ .Values.token_public_key_pem | b64enc }}
