kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "pulp.fullname" . }}-storage
  labels:
    {{- include "pulp.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
